### ISSUE TITLE
Fatal error: Uncaught Error: Cannot use object of type UFWP_Course as array in ...

### ISSUE THREAD

**Issue by flowdee** [flowdee/wp-udemy#18]
`Fatal error: Uncaught Error: Cannot use object of type UFWP_Course as array in /srv/users/serverpilot/apps/thebestsportgear/public/wp-content/plugins/wp-udemy-pro/includes/click-tracking.php:25 Stack trace: #0 /srv/users/serverpilot/apps/thebestsportgear/public/wp-includes/class-wp-hook.php(286): ufwp_pro_click_tracking_container_attributes(Array, Object(UFWP_Course)) #1 /srv/users/serverpilot/apps/thebestsportgear/public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /srv/users/serverpilot/apps/thebestsportgear/public/wp-content/plugins/wp-udemy/includes/class.course.php(84): apply_filters('ufwp_course_con...', Array, Object(UFWP_Course)) #3 /srv/users/serverpilot/apps/thebestsportgear/public/wp-content/plugins/wp-udemy/templates/grid.php(26): UFWP_Course->the_container() #4 /srv/users/serverpilot/apps/thebestsportgear/public/wp-content/plugins/wp-udemy/includes/functions.php(396): include('/srv/users/serv...') #5 /srv/users/serverpilot/apps/thebestsportgear/public/wp-content/plugins/wp-udemy/includ in /srv/users/serverpilot/apps/thebestsportgear/public/wp-content/plugins/wp-udemy-pro/includes/click-tracking.php on line 25`

**Comment by flowdee** [comment]
- https://secure.helpscout.net/conversation/470012779/3837/
